# Generated by Django 4.2.22 on 2025-06-06 08:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('dni', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='DNI debe tener formato: 12345678A', regex='^[0-9]{8}[A-Za-z]$')], verbose_name='DNI')),
                ('categoria', models.CharField(choices=[('White', 'White'), ('Black', 'Black')], max_length=10, verbose_name='Categoría')),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], max_length=20, verbose_name='Método de pago')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_renovacion', models.DateField(verbose_name='Fecha de renovación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio €')),
                ('remanente_pepe', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para PEPE-normal Black', max_digits=10, null=True, verbose_name='Remanente PEPE')),
                ('remanente_pepe_video', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para PEPE-videoCall Black', max_digits=10, null=True, verbose_name='Remanente PEPE Video')),
                ('remanente_dani', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para Dani-Rubi Black', max_digits=10, null=True, verbose_name='Remanente Dani')),
                ('remanente_aven', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para Dani Black', max_digits=10, null=True, verbose_name='Remanente Aven')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cliente activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_line', models.ForeignKey(help_text='Línea específica: PEPE-normal, Dani-Rubi, etc.', on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='business_lines.businessline', verbose_name='Línea de negocio')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['business_line__name', 'categoria', 'nombre'],
                'unique_together': {('dni', 'business_line')},
            },
        ),
    ]
