# Generated by Django 4.2.22 on 2025-06-06 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Jaen, PEPE, PEPE-normal', max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Se genera automáticamente', max_length=120, unique=True, verbose_name='Slug')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='1=Principal (Jaen), 2=Sublínea (PEPE), 3=Sub-sublínea (PEPE-normal)', verbose_name='Nivel')),
                ('has_remanente', models.BooleanField(default=False, help_text='Si esta línea maneja remanentes en categoría Black', verbose_name='Tiene remanente')),
                ('remanente_field', models.CharField(blank=True, help_text='Campo específico: remanente_pepe, remanente_dani, etc.', max_length=50, verbose_name='Campo de remanente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Para crear jerarquía: Jaen -> PEPE -> PEPE-normal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='business_lines.businessline', verbose_name='Línea padre')),
            ],
            options={
                'verbose_name': 'Línea de Negocio',
                'verbose_name_plural': 'Líneas de Negocio',
                'ordering': ['level', 'name'],
                'unique_together': {('name', 'parent')},
            },
        ),
    ]
